### ISSUE TITLE
LED-Streifen zum Schneiden (Sven)

### ISSUE THREAD

**Issue by urbaninnovation** [urbaninnovation/xmaslight#1]

**Comment by urbaninnovation** [comment]
https://shop.pimoroni.de/collections/adafruit/products/adafruit-neopixel-ring-24-x-rgb-led-w-integrated-drivers

**Comment by gwelt** [comment]
https://www.amazon.de/gp/product/B00KGGPGB6/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1

**Comment by gwelt** [comment]
Ist geliefert.
