### ISSUE TITLE
node.js code zum steuern der RGB LED STRIPS

### ISSUE THREAD

**Issue by urbaninnovation** [urbaninnovation/xmaslight#7]
beyondscreen/node-rpi-ws281x-native

**Comment by gwelt** [comment]
funktioniert - aber nur, wenn der Client mit Rootrechten gestartet wird...
...muss besser.

**Comment by gwelt** [comment]
Image ist nun mit pm2 und Start mit Rootrechten bespielt. Andere Lösung scheint es nicht zu geben.
